sistema/sistema/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import Login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('veiculos/', include(('veiculos.urls','veiculos'), namespace='veiculos')),
    path('',Login.as_view(),name='index')
]

sistema/veiculos/urls.py
from django.urls import path

from veiculos.views import VeiculoUpdate
from veiculos.views import VeiculosList
from veiculos.views import VeiculoInfo
from veiculos.views import VeiculoCreate
from veiculos.views import VeiculoDelete
from veiculos.views import VeiculosListAPI

urlpatterns = [
    path('', VeiculosList.as_view(),name='listar-veiculos'),
    path('criar/', VeiculoCreate.as_view(), name='criar-veiculo'),
    path('editar/<int:pk>', VeiculoUpdate.as_view(), name='editar-veiculo'),
    path('deletar/<int:pk>', VeiculoDelete.as_view(), name='deletar-veiculo'),
    path('<int:pk>', VeiculoInfo.as_view(), name='info-veiculo'),
    path('api/listar/', VeiculosListAPI.as_view(), name='api-listar-veiculo'),
]

sistema/sistema/views/login.py
import logging

from django.contrib.auth import authenticate,login
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import View

logger = logging.getLogger(__name__)
# Create your views here.
class Login(View):
    def get(self,req):
        contexto = {
            'usuario': '',
            'senha': ''
        }
        return render(req,'login/login.html',contexto)

    def post(self, req):
        usuario=req.POST.get('usuario', None)
        senha = req.POST.get('senha',None)
        logger.info(f"Usuario: {usuario}")
        logger.info(f"Senha: {senha}")
        user = authenticate(req, username=usuario,password=senha)
        if user:
            if user.is_active:
                login(req,user)
                return redirect('/veiculos')
            return render(req,'login/login.html',{})
        return render(req,'login/login.html',{})

sistema/veiculos/views/VeiculoCreate.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator

from veiculos.views.form import FormularioVeiculo
from django.views.generic import CreateView
from veiculos.models import Veiculo

from sistema.utilitarios import AutenticacaoObrigatoria

class VeiculoCreate(AutenticacaoObrigatoria,CreateView):
    """
    View para Criar veiculos cadastrados.
    """
    model = Veiculo
    template_name = 'veiculos/criar.html'
    form_class = FormularioVeiculo

    def post(self, request, *args, **kwargs):
        form = FormularioVeiculo(request.POST)
        if form.is_valid():
            veiculo = form.save()
            veiculo.save()
            return HttpResponseRedirect(reverse('veiculos:listar-veiculos'))
        return render(request, reverse('veiculos:criar-veiculo'), {'form': form})

sistema/veiculos/views/VeiculoDelete.py
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from veiculos.models import Veiculo

from sistema.utilitarios import AutenticacaoObrigatoria

class VeiculoDelete(AutenticacaoObrigatoria,DeleteView):
    """
    View para deletar veiculos cadastrados.
    """
    model = Veiculo
    template_name = 'veiculos/deletar.html'
    success_url = reverse_lazy('veiculos:listar-veiculos')

sistema/veiculos/views/VeiculoInfo.py
from django.views.generic import DetailView
from veiculos.models import Veiculo

from sistema.utilitarios import AutenticacaoObrigatoria


class VeiculoInfo(AutenticacaoObrigatoria, DetailView):
    """
    View para Detalhar veiculos cadastrados.
    """
    model = Veiculo
    context_object_name = 'veiculo'
    template_name = 'veiculos/info.html'

sistema/veiculos/views/VeiculoList.py
from django.views.generic import ListView
from veiculos.models import Veiculo

from sistema.utilitarios import AutenticacaoObrigatoria


class VeiculosList(AutenticacaoObrigatoria,ListView):
    """
    View para listar veiculos cadastrados.
    """
    model = Veiculo
    context_object_name = 'lista_veiculos'
    template_name = 'veiculos/listar.html'

sistema/veiculos/views/VeiculoUpdate.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from django.views.generic import UpdateView

from veiculos.views.form.FormularioVeiculo import FormularioVeiculo
from veiculos.models import Veiculo

from sistema.utilitarios import AutenticacaoObrigatoria


class VeiculoUpdate(AutenticacaoObrigatoria,UpdateView):
    """
    View para editar veiculos cadastrados.
    """
    model = Veiculo
    template_name = 'veiculos/editar.html'
    form_class = FormularioVeiculo

    def post(self, request, *args, **kwargs):
        form = FormularioVeiculo(request.POST)
        if form.is_valid():
            veiculo = form.save()
            veiculo.save()
            return HttpResponseRedirect(reverse('veiculos:listar-veiculos'))
        return render(request, reverse('veiculos:editar-veiculo'), {'form': form})

sistema/templates/login/login.html
{% load static %}

<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Bootstrap Stylesheets-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!--Icons-->
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!--Custom stylesheets-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>

<body>

    <div class="login-area">
        <div class="container">
            <div class="login-box">
                <form method="post" action="/">
                    {% csrf_token %}
                    <div class="login-form-head">
                        <h4>Entrar</h4>
                        <p>Olá, faça login para acesso ao site</p>
                    </div>
                    <div class="login-form-body">
                        <div class="form-gp">
                            <label for="user">Usuário</label>
                            <input type="text" id="user" name="usuario" value="{{ usuario }}">
                            <i class="ti-user"></i>
                        </div>
                        <div class="form-gp">
                            <label for="senha">Senha</label>
                            <input type="password" id="senha" name="senha" value="{{ senha }}">
                            <i class="ti-lock"></i>
                        </div>
                        <div class="submit-btn-area">
                            <button type="submit">Entrar <i class="ti-arrow-right"></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

    <script >
        $('.form-gp input').on('focus', function() { //Quando o foco é o input (for editar)
            $(this).parent('.form-gp').addClass('focused'); // Coloca o estilo da classe focused, na qual a label vai para cima do input(deixa de ser um 'placeholder')
        });
        $('.form-gp input').on('focusout', function() { //Quando o foco não é o input
            if ($(this).val().length === 0) { // Se o input estiver vazio, ele retira a classe 'focused' e a label volta a posição original como 'placeholder'
                $(this).parent('.form-gp').removeClass('focused');
            }
        });
    </script>
</body>
</html>

sistema/veiculos/templates/veiculos/criar.html
{% extends 'veiculos/listar.html'%}
{% load static %}
{% block titulo%}Cadastrar Veiculo{%endblock%}
{% block header%}Cadastrar Veiculo{%endblock%}

{% block container%}
	<form method="post">
		{% csrf_token %}
		{% for field in form.visible_fields %}
			<div class="form-group">
			{{ field.label_tag }}
			{{field}}
			{% if field.help_text %}
				<small id="{{field.id_for_label}}Help" class="form-text text-muted">{{field.help_text}}</small>
			{% endif %}
			</div>
		{% endfor %}
		<a class="btn btn-danger" href="{% url 'veiculos:listar-veiculos'%}"><i class="ti-close"></i> Cancelar</a>
		<button class="btn btn-success" type="submit"><i class="ti-save"></i> Salvar</button>
	</form>
{%endblock%}

sistema/veiculos/templates/veiculos/deletar.html
{% extends 'veiculos/listar.html'%}
{% load static %}
{% block titulo%}Visualizar Veiculo{%endblock%}
{% block header%}Visualizar Veiculo{%endblock%}

{% block container%}
<form method="post">
	{% csrf_token %}
	<div class="form-group">
		<span>Tem certeza que você quer deletar o veiculo "{{ object }}"?</span>
	</div>
	<button class="btn btn-success" type="submit"><i class="ti-check"></i> Sim</button>
	<a class="btn btn-danger" href="{% url 'veiculos:listar-veiculos'%}"><i class="ti-close"></i> Não</a>

</form>
{%endblock%}

sistema/veiculos/templates/veiculos/editar.html
{% extends 'veiculos/listar.html'%}
{% load static %}
{% block titulo%}Editar Veiculo{%endblock%}
{% block header%}Editar Veiculo{%endblock%}

{% block container%}
	<form method="post">
		{% csrf_token %}
		{% for field in form.visible_fields %}
			<div class="form-group">
			{{ field.label_tag }}
			{{field}}
			{% if field.help_text %}
				<small id="{{field.id_for_label}}Help" class="form-text text-muted">{{field.help_text}}</small>
			{% endif %}
			</div>
		{% endfor %}
		<button class="btn btn-success" type="submit"><i class="ti-save"></i> Salvar</button>
	</form>
{%endblock%}

sistema/veiculos/templates/veiculos/info.html
{% extends 'veiculos/listar.html'%}
{% load static %}
{% block titulo%}Visualizar Veiculo{%endblock%}
{% block header%}Visualizar Veiculo{%endblock%}

{% block container%}
<h1 class="card-title pricing-card-title">{{veiculo.modelo}} <small class="text-muted">{{veiculo.marca}}</small></h1>
<ul class="list-unstyled mt-3 mb-4">
	<li>Valor: R$ {{veiculo.valor}}</li>
	<li>Ano:{{veiculo.ano_fabricacao}}/{{veiculo.modelo_fabricacao}}</li>
	<li>Combustivel: {{veiculo.get_combustivel_display}}</li>
</ul>
<a class="btn btn-info" href="{% url 'veiculos:listar-veiculos'%}" role="button"><i class="ti-arrow-circle-left"></i> Voltar</a>
<a class="btn btn-warning" href="{% url 'veiculos:editar-veiculo' pk=veiculo.pk%}" role="button"><i class="ti-pencil"></i> Editar</a>
{%endblock%}

sistema/veiculos/templates/veiculos/listar.html
{% load static %}

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block titulo %}Lista de Veiculos{% endblock%}</title>

    <!--Bootstrap Stylesheets-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet">

	<!--Icons-->
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!--Custom stylesheets-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>

<body>

	<!-- Content Wrapper -->
	<div class="content-area">
		<div class="container">
		<!-- Topbar -->
		<nav class="navbar navbar-expand topbar static-top rounded p-1 px-4 my-2">
			<h1 class="h3 my-2 text-gray-800">{% block header %}Lista de Veiculos{% endblock%}</h1>
			<!-- Topbar Navbar -->
			<ul class="navbar-nav ml-auto">

				<!-- Nav Item - User Information -->
				<li class="nav-item dropdown text-primary">
					<a class="nav-link dropdown-toggle text-primary" href="#" id="userDropdown" role="button"
						data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<span class="mr-2 d-none d-lg-inline small">{{user}}</span>
						<img class="img-profile rounded-circle"
							src="{% static 'img/undraw_profile.svg' %}">
					</a>
					<!-- Dropdown - User Information -->
					<div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
						aria-labelledby="userDropdown">
						<a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
							<i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
							Sair
						</a>
					</div>
				</li>

			</ul>

		</nav>
		<!-- End of Topbar -->

		<!-- Begin Page Content -->
		<div class="container-fluid">

			   <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-body">
							{% block container%}
                            <div class="table-responsive">
                                <table class="table table-striped" id="lista-veiculo" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Modelo</th>
                                            <th>Marca</th>
                                            <th>Valor</th>
                                            <th>Ano fabricação</th>
                                            <th>Modelo Fabricação</th>
                                            <th>Combustivel</th>
											<th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
									{% for veiculo in lista_veiculos%}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>{{veiculo.modelo}}</td>
                                            <td>{{veiculo.marca}}</td>
                                            <td>R$ {{veiculo.valor}}</td>
                                            <td>{{veiculo.ano_fabricacao}}</td>
                                            <td>{{veiculo.modelo_fabricacao}}</td>
                                            <td>{{veiculo.get_combustivel_display}}</td>
											<td>
												<a class="btn btn-info" href="{% url 'veiculos:info-veiculo' pk=veiculo.pk%}" role="button"><i class="ti-info-alt"></i></a>
												<a class="btn btn-warning" href="{% url 'veiculos:editar-veiculo' pk=veiculo.pk%}" role="button"><i class="ti-pencil"></i></a>
												<a class="btn btn-danger" href="{% url 'veiculos:deletar-veiculo' pk=veiculo.pk%}" role="button"><i class="ti-trash"></i></a>

											</td>
                                        </tr>
									{% endfor%}
                                    </tbody>
									<tfoot>
										<tr>
										  <td colspan="7"><a class="btn btn-info" href="{% url 'veiculos:criar-veiculo' %}" role="button"><i class="ti-plus"></i> Novo Veiculo</a></td>
										</tr>
									</tfoot>
                                </table>
                            </div>
							{%endblock%}
                        </div>
                    </div>


		</div>
		<!-- /.container-fluid -->

		<!-- Footer -->
		<footer class="sticky-footer">
			<div class="container my-auto">
				<div class="copyright text-center my-auto">
					<span>Copyright &copy; Your Website 2020</span>
				</div>
			</div>
		</footer>
		<!-- End of Footer -->
		</div>
	</div>
	<!-- End of Content Wrapper -->

 	<!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

	<!-- Page level plugins -->
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>

    <!-- Custom scripts for all pages
    <script src="js/sb-admin-2.min.js"></script>-->
	<script type="text/javascript">
		$(document).ready(function() {
			$('#lista-veiculo').DataTable( {
				"language": {
					"lengthMenu": "Mostrar _MENU_ veiculos por páginas",
					"zeroRecords": "Sem registro de veiculos",
					"info": "Exibindo _PAGE_ de _PAGES_",
					"infoEmpty": "Sem veiculos com tal parametro",
					"infoFiltered": "(Filtrado de _MAX_ registros totais)",
					"previous":"Anterior",
					"next":"Próxima"
				},
				columnDefs: [
					{ orderable: false, targets: 6 }
				]
			}
    	);
		} );
	</script>

</body>

</html>